# Создание словаря с тестами

In [2]:
test_dict = {
}

## torch.six() ([#94709](https://github.com/pytorch/pytorch/pull/94709))

Модуль для совместиости Python 2 и 3.x был удалён 

In [3]:
test_dict['torch._six'] = "import torch._six"

### v1.0.0

In [1]:
import torch._six

### v2.7.0

In [1]:
import torch._six

ModuleNotFoundError: No module named 'torch._six'

## torch.qr() ([#69857](https://github.com/pytorch/pytorch/pull/69857))

Разложение QR на множетели.

In [4]:
test_dict['torch.qr'] = """
import torch
result = torch.qr(torch.tensor([[1.0, 2.0], [3.0, 4.0]]))
print(result)
"""

### v1.0.0

In [1]:
import torch
print('PyTorch',torch.__version__)

result = torch.qr(torch.tensor([[1.0, 2.0], [3.0, 4.0]]))
print(result)

PyTorch 1.0.0
(tensor([[-0.3162, -0.9487],
        [-0.9487,  0.3162]]), tensor([[-3.1623, -4.4272],
        [ 0.0000, -0.6325]]))


### v2.7.0

Работает, но предупреждает, что метод устарел

In [1]:
import torch
print('PyTorch',torch.__version__)

result = torch.qr(torch.tensor([[1.0, 2.0], [3.0, 4.0]]))
print(result)

PyTorch 2.7.0+cpu
torch.return_types.qr(
Q=tensor([[-0.3162, -0.9487],
        [-0.9487,  0.3162]]),
R=tensor([[-3.1623, -4.4272],
        [ 0.0000, -0.6325]]))


C:\Users\sinde\AppData\Local\Temp\ipykernel_20888\3439701984.py:4: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\BatchLinearAlgebra.cpp:2493.)
  result = torch.qr(torch.tensor([[1.0, 2.0], [3.0, 4.0]]))


## cholesky() ([#69857](https://github.com/pytorch/pytorch/pull/69857))

In [5]:
test_dict["torch.cholesky_solve"] = """
import torch
U = torch.tensor([[1.0, 2.0], [0.0, 1.0]])
result = torch.cholesky(U)
print(result)"""

### v1.0.0

In [1]:
import torch
print('PyTorch:', torch.__version__)

U = torch.tensor([[1.0, 2.0], [0.0, 1.0]])
result = torch.cholesky(U)
print(result)

PyTorch: 1.0.0
tensor([[1., 0.],
        [0., 1.]])


### v2.7.0

Работает, но выдаёт предупреждение о том что функция устарела.

In [1]:
import torch
print('PyTorch:', torch.__version__)

U = torch.tensor([[1.0, 2.0], [0.0, 1.0]])
result = torch.cholesky(U)
print(result)

PyTorch: 2.7.0+cpu
tensor([[1., 0.],
        [0., 1.]])


C:\Users\sinde\AppData\Local\Temp\ipykernel_7496\3599700712.py:5: UserWarning: torch.cholesky is deprecated in favor of torch.linalg.cholesky and will be removed in a future PyTorch release.
L = torch.cholesky(A)
should be replaced with
L = torch.linalg.cholesky(A)
and
U = torch.cholesky(A, upper=True)
should be replaced with
U = torch.linalg.cholesky(A).mH
This transform will produce equivalent results for all valid (symmetric positive definite) inputs. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\BatchLinearAlgebra.cpp:1767.)
  result = torch.cholesky(U)


## torch.potri() ([#22841](https://github.com/pytorch/pytorch/pull/22841))

In [6]:
test_dict["torch.potri"] = """
import torch
a = torch.tensor([[1.0, 0.2], [0.0, 1.9]])
u = torch.cholesky(a)
result = torch.potri(u)
print(result)
"""

### v1.0.0

In [ ]:
import torch
print('PyTorch:', torch.__version__)

a = torch.tensor([[1.0, 0.2], [0.0, 1.9]])
u = torch.cholesky(a)
result = torch.potri(u)
print(result)

PyTorch: 1.0.0
tensor([[1.0000, -0.0000],
        [-0.0000, 0.5263]])


### v2.7.0

In [ ]:
import torch
print('PyTorch:', torch.__version__)

a = torch.tensor([[1.0, 0.2], [0.0, 1.9]])
u = torch.cholesky(a)
result = torch.potri(u)
print(result)

PyTorch: 2.7.0+cpu


C:\Users\sinde\AppData\Local\Temp\ipykernel_18612\2721103264.py:4: UserWarning: torch.cholesky is deprecated in favor of torch.linalg.cholesky and will be removed in a future PyTorch release.
L = torch.cholesky(A)
should be replaced with
L = torch.linalg.cholesky(A)
and
U = torch.cholesky(A, upper=True)
should be replaced with
U = torch.linalg.cholesky(A).mH
This transform will produce equivalent results for all valid (symmetric positive definite) inputs. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\BatchLinearAlgebra.cpp:1767.)
  u = torch.cholesky(a)


AttributeError: module 'torch' has no attribute 'potri'

## torch.trtrs ([#22841](https://github.com/pytorch/pytorch/pull/22841))

In [7]:
test_dict["torch.trtrs"] = """
import torch

a = torch.triu(torch.randn(3,3))
b = torch.randn(3,1)
solution, cloned_a = torch.trtrs(b, a)
print(solution) 
print(cloned_a)
"""

### v1.0.0

In [3]:
import torch
print('PyTorch:', torch.__version__)

a = torch.triu(torch.randn(3,3))
b = torch.randn(3,1)
solution, cloned_a = torch.trtrs(b, a)
print(solution) 
print(cloned_a)

PyTorch: 1.0.0
tensor([[-1.4166],
        [-0.5993],
        [ 1.2320]])
tensor([[ 1.7628,  0.3828,  1.4104],
        [ 0.0000,  0.9611, -0.5843],
        [ 0.0000,  0.0000,  1.2571]])


### v2.7.0

In [1]:
import torch
print('PyTorch:', torch.__version__)

a = torch.triu(torch.randn(3,3))
b = torch.randn(3,1)
solution, cloned_a = torch.trtrs(b, a)
print(solution) 
print(cloned_a)

PyTorch: 2.7.0+cpu


AttributeError: module 'torch' has no attribute 'trtrs'

## zero_grad() в оптимизаторах ([#92731](https://github.com/pytorch/pytorch/pull/92731))

In [8]:
test_dict["zero_grad()"] = """import torch
model = torch.nn.Linear(1, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

x = torch.tensor([[1.0]])
y = model(x)
y.sum().backward()

optimizer.zero_grad()
for param in model.parameters():
    # добавим строчку с ошибкой для новых версий
    param.grad + 1
"""

### v1.0.0

In [ ]:
import torch
print("PyTorch:", torch.__version__)

model = torch.nn.Linear(1, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

x = torch.tensor([[1.0]])
y = model(x)
y.sum().backward()

optimizer.zero_grad()
for param in model.parameters():
    print(param.grad)

PyTorch: 1.0.0
tensor([[0.]])
tensor([0.])


In [2]:
for param in model.parameters():
    print(param.grad + 1)

tensor([[1.]])
tensor([1.])


### v2.7.0

In [ ]:
import torch
print("PyTorch:", torch.__version__)

model = torch.nn.Linear(1, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

x = torch.tensor([[1.0]])
y = model(x)
y.sum().backward()

optimizer.zero_grad()
for param in model.parameters():
    print(param.grad)

PyTorch: 2.7.0+cpu
None
None


In [2]:
for param in model.parameters():
    print(param.grad + 1)

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

## torch.stft() ([#86724](https://github.com/pytorch/pytorch/pull/86724))

In [9]:
test_dict["torch.stft()"] = """import torch  
signal = torch.randn(100)  
stft = torch.stft(signal, n_fft=16) 
print(stft.dtype)"""

### v1.0.0

In [1]:
import torch
print("PyTorch:", torch.__version__)

signal = torch.randn(100)  
stft = torch.stft(signal, n_fft=16) 
print(stft.dtype)

PyTorch: 1.0.0
torch.float32


### v2.7.0

In [2]:
import torch  
print("PyTorch:", torch.__version__)

signal = torch.randn(100)  
stft = torch.stft(signal, n_fft=16) 
print(stft.dtype)

PyTorch: 2.7.0+cpu


RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.

## torch.nn.functional.scaled_dot_product_attention() ([New Features](https://newreleases.io/project/github/pytorch/pytorch/release/v2.0.0#:~:text=Add%20torch.nn.functional.scaled_dot_product_attention()%20to%20allow%20writing%20fast%20Transformer%2Dlike%20functions%20and%20use%20it%20to%20speed%20up%20nn.Transformer()%20(%20%2391362%2C%20%2391066%2C%20%2390413%2C%20%2387312%2C%20%2394008%2C%20%2389470%2C%20%2390776%2C%20%2392189)))

In [10]:
test_dict["torch.nn.functional.scaled_dot_product_attention()"] = """
import torch  
q = torch.tensor([[0.1, 0.2, 0.3, 0.3, 0.5]]) 
k = torch.tensor([[0.7, 0.3, 0.7, 0.2, 0.9]]) 
v = torch.tensor([[0.2, 0.4, 0.4, 0.75, 0.1]]) 
attn = (q @ k.transpose(-2,-1)) / (10**0.5)  
attn = torch.softmax(attn, dim=-1) @ v
print(attn)"""

### v1.0.0

In [8]:
import torch  
print('PyTorch:', torch.__version__)

q = torch.tensor([[0.1, 0.2, 0.3, 0.3, 0.5]]) 
k = torch.tensor([[0.7, 0.3, 0.7, 0.2, 0.9]]) 
v = torch.tensor([[0.2, 0.4, 0.4, 0.75, 0.1]]) 
attn = (q @ k.transpose(-2,-1)) / (10**0.5)  
attn = torch.softmax(attn, dim=-1) @ v
print(attn)

PyTorch: 1.0.0
tensor([[0.2000, 0.4000, 0.4000, 0.7500, 0.1000]])


### v2.7.0

In [2]:
import torch
print('PyTorch:', torch.__version__)

q = torch.tensor([[0.1, 0.2, 0.3, 0.3, 0.5]]) 
k = torch.tensor([[0.7, 0.3, 0.7, 0.2, 0.9]]) 
v = torch.tensor([[0.2, 0.4, 0.4, 0.75, 0.1]]) 
attn = (q @ k.transpose(-2,-1)) / (10**0.5)  
attn = torch.softmax(attn, dim=-1) @ v
print(attn)

PyTorch: 2.7.0+cpu
tensor([[0.2000, 0.4000, 0.4000, 0.7500, 0.1000]])


Код работает в новых версиях, но его можно изменить с помощью новой функции.

In [ ]:
q = torch.tensor([[0.1, 0.2, 0.3, 0.3, 0.5]]) 
k = torch.tensor([[0.7, 0.3, 0.7, 0.2, 0.9]]) 
v = torch.tensor([[0.2, 0.4, 0.4, 0.75, 0.1]]) 
attn = torch.nn.functional.scaled_dot_product_attention(q, k, v)
print(attn)

tensor([[0.2000, 0.4000, 0.4000, 0.7500, 0.1000]])


## Пользовательская EmbedModel 

!Подробное описание кода ниже в версиях

In [11]:
test_dict["EmbedModel"] = """
import torch
import torch.nn as nn

class EmbeddingModel(nn.Module):
    def __init__(self, vocab_size, embed_dim):
        super(EmbeddingModel, self).__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim)

    def forward(self, x):
        embeds = self.embed(x)
        A = torch.randn(embeds.size(1), embeds.size(1))
        b = embeds.t()
        # torch.gesv заменена в новых версиях.(решает систему Ax=b)
        # в новой версии используется torch.solve(b, A)[0]
        solution = torch.gesv(b, A)[0]
        embeds = solution.t()
        return embeds

vocab_size = 100  
embed_dim = 5  
epochs = 100  
learning_rate = 0.01  
model = EmbeddingModel(vocab_size, embed_dim)  
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  
criterion = nn.MSELoss()  
x_train = torch.tensor([1, 2, 3])  
y_train = torch.tensor([[0.1, 0.2, 0.3, 0.4, 0.5], 
                        [0.2, 0.3, 0.4, 0.5, 0.6], 
                        [0.3, 0.4, 0.5, 0.6, 0.7]])  
for epoch in range(epochs):  
    model.train()  
    outputs = model(x_train)  
    loss = criterion(outputs, y_train)  
    optimizer.zero_grad()  # в новых версиях изменяется на None, в старых приводилось к 0
    loss.backward()  
    optimizer.step()  

print('End train model')"""

### v1.0.0

In [2]:
import torch
import torch.nn as nn
print('PyTorch:', torch.__version__)

class EmbeddingModel(nn.Module):
    def __init__(self, vocab_size, embed_dim):
        super(EmbeddingModel, self).__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim)

    def forward(self, x):
        embeds = self.embed(x)
        A = torch.randn(embeds.size(1), embeds.size(1))
        b = embeds.t()
        # torch.gesv заменена в новых версиях.(решает систему Ax=b)
        # в новой версии используется torch.solve(b, A)[0]
        solution = torch.gesv(b, A)[0]
        embeds = solution.t()
        return embeds

vocab_size = 100  
embed_dim = 5  
epochs = 100  
learning_rate = 0.01  
model = EmbeddingModel(vocab_size, embed_dim)  
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  
criterion = nn.MSELoss()  
x_train = torch.tensor([1, 2, 3])  
y_train = torch.tensor([[0.1, 0.2, 0.3, 0.4, 0.5], 
                        [0.2, 0.3, 0.4, 0.5, 0.6], 
                        [0.3, 0.4, 0.5, 0.6, 0.7]])  
for epoch in range(epochs):  
    model.train()  
    outputs = model(x_train)  
    loss = criterion(outputs, y_train)  
    optimizer.zero_grad()  # в новых версиях изменяется на None, в старых приводилось к 0
    loss.backward()  
    optimizer.step()  

print('End train model')

PyTorch: 1.0.0
End train model


### v2.7.0

In [1]:
import torch
import torch.nn as nn
print('PyTorch:', torch.__version__)

class EmbeddingModel(nn.Module):
    def __init__(self, vocab_size, embed_dim):
        super(EmbeddingModel, self).__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim)

    def forward(self, x):
        embeds = self.embed(x)
        A = torch.randn(embeds.size(1), embeds.size(1))
        b = embeds.t()
        solution = torch.gesv(b, A)[0]
        embeds = solution.t()
        return embeds

vocab_size = 100  
embed_dim = 5  
epochs = 100  
learning_rate = 0.01  
model = EmbeddingModel(vocab_size, embed_dim)  
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  
criterion = nn.MSELoss()  
x_train = torch.tensor([1, 2, 3])  
y_train = torch.tensor([[0.1, 0.2, 0.3, 0.4, 0.5], 
                        [0.2, 0.3, 0.4, 0.5, 0.6], 
                        [0.3, 0.4, 0.5, 0.6, 0.7]]) 

for epoch in range(epochs):  
    model.train()  
    outputs = model(x_train)  
    loss = criterion(outputs, y_train)  
    optimizer.zero_grad()  
    loss.backward()  
    optimizer.step()  

print('End train model')

PyTorch: 2.7.0+cpu


AttributeError: module 'torch' has no attribute 'gesv'

## Созранение словаря с тестами

In [12]:
test_dict

{'torch._six': 'import torch._six',
 'torch.qr': '\nimport torch\nresult = torch.qr(torch.tensor([[1.0, 2.0], [3.0, 4.0]]))\nprint(result)\n',
 'torch.cholesky_solve': '\nimport torch\nU = torch.tensor([[1.0, 2.0], [0.0, 1.0]])\nresult = torch.cholesky(U)\nprint(result)',
 'torch.potri': '\nimport torch\na = torch.tensor([[1.0, 0.2], [0.0, 1.9]])\nu = torch.cholesky(a)\nresult = torch.potri(u)\nprint(result)\n',
 'torch.trtrs': '\nimport torch\n\na = torch.triu(torch.randn(3,3))\nb = torch.randn(3,1)\nsolution, cloned_a = torch.trtrs(b, a)\nprint(solution) \nprint(cloned_a)\n',
 'zero_grad()': 'import torch\nmodel = torch.nn.Linear(1, 1)\noptimizer = torch.optim.SGD(model.parameters(), lr=0.1)\n\nx = torch.tensor([[1.0]])\ny = model(x)\ny.sum().backward()\n\noptimizer.zero_grad()\nfor param in model.parameters():\n    # добавим строчку с ошибкой для новых версий\n    param.grad + 1\n',
 'torch.stft()': 'import torch  \nsignal = torch.randn(100)  \nstft = torch.stft(signal, n_fft=16) \n

In [13]:
import json

with open("old_code.json", "w") as file:
    json.dump(test_dict, file)